M48
; DRILL file {KiCad 9.0.3} date 2025-07-29T19:30:15-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-29T19:30:15-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X189.34Y-92.0
X199.5Y-92.0
T2
X194.42Y-92.0
M30
